<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Illuminate\Database\Eloquent\Relations\HasOne;
use Illuminate\Database\Eloquent\Relations\HasMany;
use App\Models\Proposal;

use Spatie\Permission\Traits\HasRoles;
use Spatie\Activitylog\Traits\LogsActivity;
use Spatie\Activitylog\LogOptions;

class User extends Authenticatable
{
    /** @use HasFactory<\Database\Factories\UserFactory> */
    use HasFactory, Notifiable, HasRoles, LogsActivity;

    public function getActivitylogOptions(): LogOptions
    {
        return LogOptions::defaults()
            ->logOnly(['name', 'email', 'role', 'is_verified', 'status'])
            ->logOnlyDirty()
            ->dontSubmitEmptyLogs()
            ->setDescriptionForEvent(fn(string $eventName) => "User has been {$eventName}");
    }

    /**
     * The attributes that are mass assignable.
     *
     * @var list<string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
        'role',
        'status',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var list<string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * Get the attributes that should be cast.
     *
     * @return array<string, string>
     */
    protected function casts(): array
    {
        return [
            'is_verified' => 'boolean',
            'email_verified_at' => 'datetime',
            'password' => 'hashed',
        ];
    }

    /**
     * Check if user is an admin.
     */
    public function isAdmin(): bool
    {
        return $this->hasRole(['admin', 'super_admin']);
    }

    /**
     * Check if user is a normal user/petani.
     */
    public function isPetani(): bool
    {
        return $this->hasRole('petani');
    }

    public function isUmum(): bool
    {
        return $this->hasRole('umum');
    }

    /**
     * Check if user is a pimpinan (leader).
     */
    public function isPimpinan(): bool
    {
        return $this->hasRole('pimpinan');
    }

    /**
     * Check if user is a Kepala Bidang (either PSP or TP).
     */
    public function isKabid(): bool
    {
        return $this->hasRole(['kabid_psp', 'kabid_tp', 'kabid_hortikultura']);
    }

    public function isKabidPsp(): bool
    {
        return $this->hasRole('kabid_psp');
    }

    public function isKabidTp(): bool
    {
        return $this->hasRole('kabid_tp');
    }

    public function isKabidHortikultura()
    {
        return $this->hasRole('kabid_hortikultura');
    }

    /**
     * Human-readable label for role.
     */
    public function getRoleLabelAttribute(): string
    {
        // Fallback to the first Spatie role if available, otherwise use legacy string
        $roleName = $this->roles->first()?->name ?? $this->role;

        return match($roleName) {
            'super_admin'=> 'Super Admin',
            'admin'      => 'Admin Dinas',
            'pimpinan'   => 'Pimpinan / Kepala Dinas',
            'kabid_psp'  => 'Kepala Bidang PSP',
            'kabid_tp'   => 'Kepala Bidang Tanaman Pangan',
            'kabid_hortikultura' => 'Kepala Bidang Hortikultura',
            'petani' => 'Kelompok Tani',
            'umum'       => 'Umum',
            default      => ucfirst($roleName),
        };
    }

    /**
     * Check if user account is approved.
     */
    /**
     * Check if user account is approved.
     */
    public function isApproved(): bool
    {
        if ($this->isAdmin() || $this->isPimpinan()) {
            return true;
        }

        return $this->status === 'approved';
    }

    /**
     * Get the farmer profile associated with the user.
     */
    public function farmerProfile(): HasOne
    {
        return $this->hasOne(FarmerProfile::class);
    }

    public function umumProfile()
    {
        return $this->hasOne(UmumProfile::class);
    }

    /**
     * Get all proposals submitted by the user.
     */
    public function proposals(): HasMany
    {
        return $this->hasMany(Proposal::class);
    }

    /**
     * Get all document signatures generated by the user.
     */
    public function documentSignatures(): HasMany
    {
        return $this->hasMany(DocumentSignature::class, 'signed_by');
    }

    /**
     * Proposals assigned to this kabid.
     */
    public function assignedProposals(): HasMany
    {
        return $this->hasMany(Proposal::class, 'kabid_id');
    }

    /**
     * Survey teams created by this kabid.
     */
    public function surveyTeams(): HasMany
    {
        return $this->hasMany(SurveyTeam::class, 'kabid_id');
    }

    protected $resolvedEmployee = null;
    protected $employeeResolved = false;

    /**
     * Get associated Employee record based on role
     */
    public function getEmployeeAttribute()
    {
        if ($this->employeeResolved) {
            return $this->resolvedEmployee;
        }

        $roleMap = [
            'pimpinan' => 'Kepala Dinas',
            'kabid_psp' => 'Kabid. PSP',
            'kabid_tp' => 'Kabid. Tanaman Pangan',
            'kabid_hortikultura' => 'Kabid. Hortikultura'
        ];
        
        if (isset($roleMap[$this->role])) {
            $this->resolvedEmployee = \App\Models\Employee::where('role', $roleMap[$this->role])->first();
        } else {
            $this->resolvedEmployee = null;
        }
        
        $this->employeeResolved = true;
        return $this->resolvedEmployee;
    }

    /**
     * Get display name, falling back to original name
     */
    public function getDisplayNameAttribute()
    {
        if ($emp = $this->employee) {
            if ($emp->name && $emp->name !== 'Belum Diisi') {
                return $emp->name;
            }
        }
        
        if ($this->isPimpinan()) return 'Pimpinan';
        if ($this->isKabidPsp()) return 'Kabid PSP';
        if ($this->isKabidTp()) return 'Kabid Tanaman Pangan';
        if ($this->isKabidHortikultura()) return 'Kabid Hortikultura';

        return $this->name;
    }
    
    /**
     * Get display foto
     */
    public function getDisplayFotoAttribute()
    {
        if ($emp = $this->employee) {
            if ($emp->foto) {
                return asset('storage/' . $emp->foto);
            }
        }
        return null;
    }
    
    /**
     * Get display NIP
     */
    public function getDisplayNipAttribute()
    {
        if ($emp = $this->employee) {
            return $emp->nip ?: '-';
        }
        return '-';
    }
}
